# Generated by Django 5.2.5 on 2025-08-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_is_group_task_alter_todo_user_group_todo_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_group_task',
        ),
    ]
